export const formFields = [
  {
    id: "medicineName",
    label: "Medicine Name*",
    type: "text",
    placeholder: "Name",
  },
  {
    id: "genericName",
    label: "Generic Name",
    type: "text",
    placeholder: "Generic Name",
  },
  {
    id: "marketedBy",
    label: "Marketed By",
    type: "text",
    placeholder: "Marketed By",
  },
  {
    id: "manufacturedBy",
    label: "Manufactured By",
    type: "text",
    placeholder: "Manufactured By",
  },
  {
    id: "unit",
    label: "Unit*",
    type: "text",
    placeholder: "Unit",
  },
  {
    id: "rackName",
    label: "Rack Name",
    type: "text",
    placeholder: "Rack Name",
  },
  {
    id: "hsnCode",
    label: "HSN Code",
    type: "text",
    placeholder: "HSN Code",
  },
  {
    id: "snowmedCtCode",
    label: "Snowmed CT Code",
    type: "text",
    placeholder: "Snowmed CT Code",
  },
  {
    id: "gstPercentage",
    label: "GST %*",
    type: "text",
    placeholder: "GST %",
  },
  {
    id: "minQuantity",
    label: "Min Quantity",
    type: "text",
    placeholder: "Min Quantity",
  },
  {
    id: "maxQuantity",
    label: "Max Quantity",
    type: "text",
    placeholder: "Max Quantity",
  },
  {
    id: "noOfUnit",
    label: "No. of Unit*",
    type: "text",
    placeholder: "No. of Unit",
  },
  {
    id: "sale",
    label: "Sale",
    type: "text",
    placeholder: "Sale",
  },
  {
    id: "mrpPerUnit",
    label: "MRP Per Unit ₹",
    type: "text",
    placeholder: "MRP Per Unit ₹",
  },
  {
    id: "expiryDate",
    label: "Expiry Date*",
    type: "date",  
    placeholder: "Expiry Date",
  },
];
