export const serviceData = {
  Services: [
    { id: 1, name: "Room Charges", rate: 5000 },
    { id: 2, name: "Day Care", rate: 10000 },
    { id: 3, name: "ICU Charges", rate: 15000 },
    { id: 4, name: "Nursing Services", rate: 3000 },
    { id: 5, name: "Doctor Consultation", rate: 2000 },
  ],
  Pharmacy: [
    { id: 1, name: "Medicines", rate: 2000 },
    { id: 2, name: "Health Supplements", rate: 1500 },
    { id: 3, name: "First Aid Supplies", rate: 500 },
    { id: 4, name: "Vaccines", rate: 3000 },
    { id: 5, name: "Surgical Items", rate: 4000 },
  ],
  Diagnostic: [
    { id: 1, name: "Blood Test", rate: 800 },
    { id: 2, name: "X-Ray", rate: 1200 },
    { id: 3, name: "MRI Scan", rate: 6000 },
    { id: 4, name: "CT Scan", rate: 5000 },
    { id: 5, name: "Ultrasound", rate: 2500 },
  ],
  Surgery: [
    { id: 1, name: "Appendectomy", rate: 50000 },
    { id: 2, name: "Gallbladder Removal", rate: 60000 },
    { id: 3, name: "Knee Replacement", rate: 120000 },
    { id: 4, name: "Cataract Surgery", rate: 40000 },
    { id: 5, name: "Hernia Repair", rate: 35000 },
  ],
  Rehabilitation: [
    { id: 1, name: "Physiotherapy", rate: 1500 },
    { id: 2, name: "Occupational Therapy", rate: 2000 },
    { id: 3, name: "Speech Therapy", rate: 1800 },
    { id: 4, name: "Chiropractic Sessions", rate: 2500 },
    { id: 5, name: "Post-Surgery Rehabilitation", rate: 4000 },
  ],
  Miscellaneous: [
    { id: 1, name: "Ambulance Services", rate: 2000 },
    { id: 2, name: "Oxygen Supply", rate: 1000 },
    { id: 3, name: "Bedside Attendant", rate: 1200 },
    { id: 4, name: "Cafeteria Services", rate: 800 },
    { id: 5, name: "Laundry Services", rate: 500 },
  ],
};

export const data = [
  {
    id: 1,
    patient: "John Doe",
    uhid: "UHID12345",
    age: 30,
    status: "Complete",
    lastVisit: "Dec 15, 2024",
    bill: "₹18,500",
    address: "123 Main Street, New Delhi, India",
  },
  {
    id: 2,
    patient: "Jane Smith",
    uhid: "UHID12346",
    age: 45,
    status: "DUE",
    lastVisit: "Nov 10, 2024",
    bill: "₹22,000",
    address: "456 Park Avenue, Mumbai, India",
  },
  {
    id: 3,
    patient: "Alex Johnson",
    uhid: "UHID12347",
    age: 25,
    status: "Complete",
    lastVisit: "Dec 5, 2024",
    bill: "₹12,000",
    address: "789 Elm Street, Bangalore, India",
  },
  {
    id: 4,
    patient: "Emily Davis",
    uhid: "UHID12348",
    age: 38,
    status: "DUE",
    lastVisit: "Dec 1, 2024",
    bill: "₹15,000",
    address: "321 Oak Road, Hyderabad, India",
  },
];
